version: '2.1'
services:
  api-gateway:
    container_name: api-gateway
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'

      # Destinos
      DESTINATIONS_URL: '172.17.0.1'
      DESTINATIONS_PORT: '3000'
      DESTINATIONS_ENTRY: 'destinations'
      
      # Eventos
      EVENTS_URL: '172.17.0.1'
      EVENTS_PORT: '3003'
      EVENTS_ENTRY: 'events'
      RESERVATIONS_URL: '172.17.0.1'
      RESERVATIONS_PORT: '3003'
      RESERVATIONS_ENTRY: 'reservations'
      
      # Register
      USERS_URL: '34.69.73.192'
      USERS_PORT: '3004'
      USERS_ENTRY: 'users'

      # Services 
      SERVICES_URL: '34.69.73.192'
      SERVICES_PORT: '3004'
      SERVICES_ENTRY: 'services'
      
      # Promociones
      PROMOCIONES_URL: '172.17.0.1'
      PROMOCIONES_PORT: '3004'
      PROMOCIONES_ENTRY: 'promociones'
      TIENDAS_URL: '172.17.0.1'
      TIENDAS_PORT: '3004'
      TIENDAS_ENTRY: 'tiendas'

      # Servidor LDAP
      LDAP_URL:  '34.69.73.192'
      LDAP_PORT: '3002'
      LDAP_ENTRYA:  'auth'
      LDAP_ENTRYAa: 'authAdmin'
      LDAP_ENTRYAd: 'add'
      LDAP_ENTRYAda: 'addAdmin'
      LDAP_ENTRYV: 'validate'

    ports:
      - '5000:5000'
